name: Build, Dockerize, and Deploy

on:
  push:

permissions:
  id-token: write
  contents: read

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up Node.js
        uses: actions/setup-node@v4.1.0
        with:
          node-version: 20

      - name: Install dependencies
        run: npm install

      - name: Build project
        run: npm run build

      - name: Build Docker image
        run: |
          docker build -t angular-app:${{ github.sha }} .
          docker tag angular-app:${{ github.sha }} ${{ secrets.ACR_LOGIN_SERVER }}/angular-app:${{ github.sha }}

      - name: Log in to Azure Container Registry using OIDC
        uses: azure/login@v2.2.0
        with:
          client-id: ${{ secrets.AZURE_CLIENT_ID }}
          tenant-id: ${{ secrets.AZURE_TENANT_ID }}
          subscription-id: ${{ secrets.AZURE_SUBSCRIPTION_ID }}
          allow-no-subscriptions: true

      - name: Authenticate Docker to Azure Container Registry
        run: az acr login --name ${{ secrets.ACR_NAME }}

      - name: Push Docker image to Azure Container Registry
        run: docker push ${{ secrets.ACR_LOGIN_SERVER }}/angular-app:${{ github.sha }}

      - name: Deploy to Azure Web App
        uses: azure/webapps-deploy@v2
        with:
          app-name: ${{ secrets.AZURE_WEBAPP_NAME }}
          images: ${{ secrets.ACR_LOGIN_SERVER }}/angular-app:${{ github.sha }}
